--
-- PostgreSQL database dump
--

\restrict aNklnEymXhMhJRkd6BIM8bnynm8CuIwXsqQBKfJpByqNNA2NFed5YYkUXn1tsjn

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: album_artists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.album_artists (
    album_id bigint NOT NULL,
    artist_id bigint NOT NULL
);


ALTER TABLE public.album_artists OWNER TO postgres;

--
-- Name: album_genres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.album_genres (
    album_id bigint NOT NULL,
    genre_id bigint NOT NULL
);


ALTER TABLE public.album_genres OWNER TO postgres;

--
-- Name: albums; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.albums (
    id bigint NOT NULL,
    release_year integer,
    title character varying(255) NOT NULL
);


ALTER TABLE public.albums OWNER TO postgres;

--
-- Name: albums_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.albums ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.albums_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: artists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.artists (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.artists OWNER TO postgres;

--
-- Name: artists_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.artists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.artists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: genres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.genres (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.genres OWNER TO postgres;

--
-- Name: genres_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tracks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tracks (
    id bigint NOT NULL,
    duration_seconds integer,
    title character varying(255) NOT NULL,
    album_id bigint,
    artist_id bigint,
    genre_id bigint
);


ALTER TABLE public.tracks OWNER TO postgres;

--
-- Name: tracks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tracks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tracks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_tracks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_tracks (
    user_id bigint NOT NULL,
    track_id bigint NOT NULL
);


ALTER TABLE public.user_tracks OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: album_artists; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.album_artists (album_id, artist_id) FROM stdin;
\.


--
-- Data for Name: album_genres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.album_genres (album_id, genre_id) FROM stdin;
\.


--
-- Data for Name: albums; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.albums (id, release_year, title) FROM stdin;
1	1982	Thriller
2	1987	Bad
3	1991	Dangerous
4	1980	Back in Black
5	1979	Highway to Hell
6	2020	Power Up
7	1973	The Dark Side of the Moon
8	1979	The Wall
9	1975	Wish You Were Here
10	1975	A Night at the Opera
11	1991	Innuendo
12	1977	News of the World
13	1986	Master of Puppets
14	1984	Ride the Lightning
15	1991	Metallica
16	1988	Группа крови
17	1989	Звезда по имени Солнце
18	1990	Черный альбом
19	1985	Это всё...
20	1992	Актриса весна
21	1999	Просвистела
22	1999	Альбом для друзей
23	2002	Пираты XXI века
24	2005	Хлеб
25	2020	Legendary Dust
26	2021	Last One
27	2021	Million Dollar: Happiness
28	2015	Дом с нормальными явлениями
29	2017	Праздник на улице 36
30	2017	Пути неисповедимы
31	2018	No Love
32	1969	Abbey Road
33	1991	Nevermind
34	1971	Led Zeppelin IV
35	1997	OK Computer
36	1971	Sticky Fingers
\.


--
-- Data for Name: artists; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.artists (id, name) FROM stdin;
1	Michael Jackson
2	AC/DC
3	Pink Floyd
4	Queen
5	Metallica
6	Кино
7	ДДТ
8	Ленинград
9	MORGENSHTERN
10	Скриптонит
11	FACE
12	The Beatles
13	Nirvana
14	Led Zeppelin
15	Radiohead
16	The Rolling Stones
\.


--
-- Data for Name: genres; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.genres (id, name) FROM stdin;
1	Pop
2	Rock
3	Progressive Rock
4	Metal
5	Hard Rock
6	Русский рок
7	Панк-рок
8	Рэп
9	Хип-хоп
10	Grunge
11	Blues Rock
12	Alternative Rock
13	Classic Rock
\.


--
-- Data for Name: tracks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tracks (id, duration_seconds, title, album_id, artist_id, genre_id) FROM stdin;
1	357	Thriller	1	\N	\N
2	258	Beat It	1	\N	\N
3	294	Billie Jean	1	\N	\N
4	363	Wanna Be Startin' Somethin'	1	\N	\N
5	245	Human Nature	1	\N	\N
6	247	Bad	2	\N	\N
7	257	Smooth Criminal	2	\N	\N
8	298	The Way You Make Me Feel	2	\N	\N
9	321	Man in the Mirror	2	\N	\N
10	281	Dirty Diana	2	\N	\N
11	235	Black or White	3	\N	\N
12	240	Remember the Time	3	\N	\N
13	367	In the Closet	3	\N	\N
14	385	Heal the World	3	\N	\N
15	255	Back in Black	4	\N	\N
16	312	Hells Bells	4	\N	\N
17	210	You Shook Me All Night Long	4	\N	\N
18	268	Rock and Roll Ain't Noise Pollution	4	\N	\N
19	208	Highway to Hell	5	\N	\N
20	204	Girls Got Rhythm	5	\N	\N
21	267	Touch Too Much	5	\N	\N
22	217	If You Want Blood	5	\N	\N
23	185	Shot in the Dark	6	\N	\N
24	187	Realize	6	\N	\N
25	210	Demon Fire	6	\N	\N
26	192	Witch's Spell	6	\N	\N
27	382	Money	7	\N	\N
28	410	Time	7	\N	\N
29	284	The Great Gig in the Sky	7	\N	\N
30	467	Us and Them	7	\N	\N
31	240	Another Brick in the Wall, Pt. 2	8	\N	\N
32	382	Comfortably Numb	8	\N	\N
33	280	Hey You	8	\N	\N
34	335	Mother	8	\N	\N
35	334	Wish You Were Here	9	\N	\N
36	810	Shine On You Crazy Diamond	9	\N	\N
37	309	Have a Cigar	9	\N	\N
38	354	Bohemian Rhapsody	10	\N	\N
39	170	You're My Best Friend	10	\N	\N
40	218	Love of My Life	10	\N	\N
41	185	I'm in Love with My Car	10	\N	\N
42	391	Innuendo	11	\N	\N
43	247	I'm Going Slightly Mad	11	\N	\N
44	273	Headlong	11	\N	\N
45	271	The Show Must Go On	11	\N	\N
46	122	We Will Rock You	12	\N	\N
47	179	We Are the Champions	12	\N	\N
48	274	Spread Your Wings	12	\N	\N
49	386	It's Late	12	\N	\N
50	515	Master of Puppets	13	\N	\N
51	313	Battery	13	\N	\N
52	397	The Thing That Should Not Be	13	\N	\N
53	387	Welcome Home (Sanitarium)	13	\N	\N
54	397	Ride the Lightning	14	\N	\N
55	309	For Whom the Bell Tolls	14	\N	\N
56	417	Fade to Black	14	\N	\N
57	396	Creeping Death	14	\N	\N
58	331	Enter Sandman	15	\N	\N
59	324	Sad But True	15	\N	\N
60	386	The Unforgiven	15	\N	\N
61	388	Nothing Else Matters	15	\N	\N
62	260	Группа крови	16	\N	\N
63	255	Закрой за мной дверь	16	\N	\N
64	235	Война	16	\N	\N
65	345	Спокойная ночь	16	\N	\N
66	225	Звезда по имени Солнце	17	\N	\N
67	315	Песня без слов	17	\N	\N
68	255	Пачка сигарет	17	\N	\N
69	235	Место для шага вперед	17	\N	\N
70	330	Кончится лето	18	\N	\N
71	310	Красно-желтые дни	18	\N	\N
72	290	Следи за собой	18	\N	\N
73	350	Это всё	19	\N	\N
74	315	Дождь	19	\N	\N
75	280	Террорист	19	\N	\N
76	295	Что такое осень	20	\N	\N
77	285	Актриса весна	20	\N	\N
78	340	Родина	20	\N	\N
79	270	Просвистела	21	\N	\N
80	320	Метель	21	\N	\N
81	290	Ветер	21	\N	\N
82	180	День рождения	22	\N	\N
83	210	Дачники	22	\N	\N
84	195	Любовь	22	\N	\N
85	190	WWW	23	\N	\N
86	185	Менеджер	23	\N	\N
87	200	Геленджик	23	\N	\N
88	175	Хлеб	24	\N	\N
89	210	Экспонат	24	\N	\N
90	190	Вояж	24	\N	\N
91	160	Cadillac	25	\N	\N
92	150	Ice	25	\N	\N
93	155	Yung Hefner	25	\N	\N
94	140	SHEESH	26	\N	\N
95	145	Cristal & МОЁТ	26	\N	\N
96	150	Show	26	\N	\N
97	135	Дуло	27	\N	\N
98	140	Новый мерин	27	\N	\N
99	145	Pablo	27	\N	\N
100	200	Притон	28	\N	\N
101	185	Танцуй сама	28	\N	\N
102	210	Космос	28	\N	\N
103	195	Ламбада	29	\N	\N
104	190	Вечеринка	29	\N	\N
105	185	Буду твоей	29	\N	\N
106	180	Юморист	30	\N	\N
107	190	Спасательный круг	30	\N	\N
108	175	Бургер	30	\N	\N
109	165	No Love	31	\N	\N
110	160	18	31	\N	\N
111	170	Кукловод	31	\N	\N
112	259	Come Together	32	\N	\N
113	182	Something	32	\N	\N
114	185	Here Comes the Sun	32	\N	\N
115	301	Smells Like Teen Spirit	33	\N	\N
116	218	Come as You Are	33	\N	\N
117	256	Lithium	33	\N	\N
118	482	Stairway to Heaven	34	\N	\N
119	294	Black Dog	34	\N	\N
120	220	Rock and Roll	34	\N	\N
121	261	Karma Police	35	\N	\N
122	387	Paranoid Android	35	\N	\N
123	228	No Surprises	35	\N	\N
124	229	Brown Sugar	36	\N	\N
125	342	Wild Horses	36	\N	\N
126	434	Can't You Hear Me Knocking	36	\N	\N
\.


--
-- Data for Name: user_tracks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_tracks (user_id, track_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name) FROM stdin;
1	Sanya
2	Andrei
3	user1337
4	user228
5	music_lover_88
6	rock_fan_2023
7	rap_enjoyer
8	metalhead_666
9	victor_tsoy_fan
10	beatles_fan
11	nirvana_lover
\.


--
-- Name: albums_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.albums_id_seq', 36, true);


--
-- Name: artists_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.artists_id_seq', 16, true);


--
-- Name: genres_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.genres_id_seq', 13, true);


--
-- Name: tracks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tracks_id_seq', 126, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 11, true);


--
-- Name: album_artists album_artists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_artists
    ADD CONSTRAINT album_artists_pkey PRIMARY KEY (album_id, artist_id);


--
-- Name: album_genres album_genres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_genres
    ADD CONSTRAINT album_genres_pkey PRIMARY KEY (album_id, genre_id);


--
-- Name: albums albums_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.albums
    ADD CONSTRAINT albums_pkey PRIMARY KEY (id);


--
-- Name: artists artists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.artists
    ADD CONSTRAINT artists_pkey PRIMARY KEY (id);


--
-- Name: genres genres_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_name_key UNIQUE (name);


--
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- Name: tracks tracks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tracks
    ADD CONSTRAINT tracks_pkey PRIMARY KEY (id);


--
-- Name: genres ukpe1a9woik1k97l87cieguyhh4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT ukpe1a9woik1k97l87cieguyhh4 UNIQUE (name);


--
-- Name: user_tracks user_tracks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_tracks
    ADD CONSTRAINT user_tracks_pkey PRIMARY KEY (user_id, track_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: album_genres album_genres_album_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_genres
    ADD CONSTRAINT album_genres_album_id_fkey FOREIGN KEY (album_id) REFERENCES public.albums(id) ON DELETE CASCADE;


--
-- Name: album_genres album_genres_genre_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_genres
    ADD CONSTRAINT album_genres_genre_id_fkey FOREIGN KEY (genre_id) REFERENCES public.genres(id) ON DELETE CASCADE;


--
-- Name: user_tracks fk6rxyg9va76kft9w44ddf52p06; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_tracks
    ADD CONSTRAINT fk6rxyg9va76kft9w44ddf52p06 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: tracks fk7weekvjfll0bifyfyx25to00l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tracks
    ADD CONSTRAINT fk7weekvjfll0bifyfyx25to00l FOREIGN KEY (genre_id) REFERENCES public.genres(id);


--
-- Name: album_genres fkd975yib1w5u2k4dpkjmswfu1y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_genres
    ADD CONSTRAINT fkd975yib1w5u2k4dpkjmswfu1y FOREIGN KEY (album_id) REFERENCES public.albums(id);


--
-- Name: tracks fkdcmijveo7n1lql01vav1u2jd2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tracks
    ADD CONSTRAINT fkdcmijveo7n1lql01vav1u2jd2 FOREIGN KEY (album_id) REFERENCES public.albums(id);


--
-- Name: tracks fkkiacd31n79ksp3mnq6owsbjiu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tracks
    ADD CONSTRAINT fkkiacd31n79ksp3mnq6owsbjiu FOREIGN KEY (artist_id) REFERENCES public.artists(id);


--
-- Name: album_genres fknc7pifo8642ai7gtk672bekkc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_genres
    ADD CONSTRAINT fknc7pifo8642ai7gtk672bekkc FOREIGN KEY (genre_id) REFERENCES public.genres(id);


--
-- Name: user_tracks fkojfgpfu9usv7xq1hasa231f9w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_tracks
    ADD CONSTRAINT fkojfgpfu9usv7xq1hasa231f9w FOREIGN KEY (track_id) REFERENCES public.tracks(id);


--
-- Name: album_artists fkpmmqobo7dghsklv6ocdqds4mb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_artists
    ADD CONSTRAINT fkpmmqobo7dghsklv6ocdqds4mb FOREIGN KEY (artist_id) REFERENCES public.artists(id);


--
-- Name: album_artists fktblxj61x9u2a4qwpbd22bjxxg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.album_artists
    ADD CONSTRAINT fktblxj61x9u2a4qwpbd22bjxxg FOREIGN KEY (album_id) REFERENCES public.albums(id);


--
-- Name: tracks tracks_album_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tracks
    ADD CONSTRAINT tracks_album_id_fkey FOREIGN KEY (album_id) REFERENCES public.albums(id) ON DELETE CASCADE;


--
-- Name: user_tracks user_tracks_track_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_tracks
    ADD CONSTRAINT user_tracks_track_id_fkey FOREIGN KEY (track_id) REFERENCES public.tracks(id) ON DELETE CASCADE;


--
-- Name: user_tracks user_tracks_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_tracks
    ADD CONSTRAINT user_tracks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict aNklnEymXhMhJRkd6BIM8bnynm8CuIwXsqQBKfJpByqNNA2NFed5YYkUXn1tsjn

