server:
    port: 8080

spring:
    application:
        name: music
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                highlight_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://localhost:5432/musicCatalog
        username: postgres
        password: password

springdoc:
    swagger-ui:
        path: /swagger-ui.html
        operations-sorter: method
        tags-sorter: alpha
    api-docs:
        path: /v3/api-docs
