server:
    port: 8080

spring:

    application:
        name: music

    jpa:
        hibernate:
        # validate проверяет соответствие сущностей таблицам БД при запуске
            ddl-auto: update
      # Включает вывод SQL-запросов в консоль
        show-sql: true
        properties:
          hibernate:
          # Делает SQL в консоли читаемым (разбивает на строки)
          format_sql: true
          # Подсвечивает ключевые слова SQL
          highlight_sql: true
          # Позволяет Hibernate корректно определять типы при использовании Postgres
          dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://localhost:5432/musicCatalog
        username: postgres
        password: password
